//
//  GameController.swift
//  Trump True or False
//
//  Created by Nelson Gonzalez on 7/11/20.
//  Copyright © 2020 Nelson Gonzalez. All rights reserved.
//

import Foundation

class GameController {
    private(set) var tweets: [Tweet] = [
    Tweet(id: 0, imageName: "0", correctAnswer: false),
    Tweet(id: 1, imageName: "1", correctAnswer: true),
    Tweet(id: 2, imageName: "2", correctAnswer: false),
    Tweet(id: 3, imageName: "3", correctAnswer: true),
    Tweet(id: 4, imageName: "4", correctAnswer: false),
    Tweet(id: 5, imageName: "5", correctAnswer: false),
    Tweet(id: 6, imageName: "6", correctAnswer: true),
    Tweet(id: 7, imageName: "7", correctAnswer: true),
    Tweet(id: 8, imageName: "8", correctAnswer: false),
    Tweet(id: 9, imageName: "9", correctAnswer: true),
    Tweet(id: 10, imageName: "10", correctAnswer: false),
    Tweet(id: 11, imageName: "11", correctAnswer: true),
    Tweet(id: 12, imageName: "12", correctAnswer: false),
    Tweet(id: 13, imageName: "13", correctAnswer: true),
    Tweet(id: 14, imageName: "14", correctAnswer: false),
    Tweet(id: 15, imageName: "15", correctAnswer: true),
    Tweet(id: 16, imageName: "16", correctAnswer: true),
    Tweet(id: 17, imageName: "17", correctAnswer: true),
    Tweet(id: 18, imageName: "18", correctAnswer: true),
    Tweet(id: 19, imageName: "19", correctAnswer: true),
    Tweet(id: 20, imageName: "20", correctAnswer: false),
    Tweet(id: 21, imageName: "21", correctAnswer: true),
    Tweet(id: 22, imageName: "22", correctAnswer: false),
    Tweet(id: 23, imageName: "23", correctAnswer: false),
    Tweet(id: 24, imageName: "24", correctAnswer: true),
    Tweet(id: 25, imageName: "25", correctAnswer: true),
    Tweet(id: 26, imageName: "26", correctAnswer: false),
    Tweet(id: 27, imageName: "27", correctAnswer: false),
    Tweet(id: 28, imageName: "28", correctAnswer: true),
    Tweet(id: 29, imageName: "29", correctAnswer: true),
    Tweet(id: 30, imageName: "30", correctAnswer: true),
    Tweet(id: 31, imageName: "31", correctAnswer: true),
    Tweet(id: 32, imageName: "32", correctAnswer: false),
    Tweet(id: 33, imageName: "33", correctAnswer: true),
    Tweet(id: 34, imageName: "34", correctAnswer: false),
    Tweet(id: 35, imageName: "35", correctAnswer: false),
    Tweet(id: 36, imageName: "36", correctAnswer: false),
    Tweet(id: 37, imageName: "37", correctAnswer: true),
    Tweet(id: 38, imageName: "38", correctAnswer: false),
    Tweet(id: 39, imageName: "39", correctAnswer: true),
    Tweet(id: 40, imageName: "40", correctAnswer: true),
    Tweet(id: 41, imageName: "41", correctAnswer: false),
    Tweet(id: 42, imageName: "42", correctAnswer: true),
    Tweet(id: 43, imageName: "43", correctAnswer: false),
    Tweet(id: 44, imageName: "44", correctAnswer: false),
    Tweet(id: 45, imageName: "45", correctAnswer: false),
    Tweet(id: 46, imageName: "46", correctAnswer: true),
    Tweet(id: 47, imageName: "47", correctAnswer: false),
    Tweet(id: 48, imageName: "48", correctAnswer: false),
    Tweet(id: 49, imageName: "49", correctAnswer: false),
    Tweet(id: 50, imageName: "50", correctAnswer: false),
    Tweet(id: 51, imageName: "51", correctAnswer: true),
    Tweet(id: 52, imageName: "52", correctAnswer: false),
    Tweet(id: 53, imageName: "53", correctAnswer: true),
    Tweet(id: 54, imageName: "54", correctAnswer: true),
    Tweet(id: 55, imageName: "55", correctAnswer: false),
    Tweet(id: 56, imageName: "56", correctAnswer: true),
    Tweet(id: 57, imageName: "57", correctAnswer: true),
    Tweet(id: 58, imageName: "58", correctAnswer: false),
    Tweet(id: 59, imageName: "59", correctAnswer: true),
    Tweet(id: 60, imageName: "60", correctAnswer: true),
    Tweet(id: 61, imageName: "61", correctAnswer: false),
    Tweet(id: 62, imageName: "62", correctAnswer: false),
    Tweet(id: 63, imageName: "63", correctAnswer: true),
    Tweet(id: 64, imageName: "64", correctAnswer: false),
    Tweet(id: 65, imageName: "65", correctAnswer: false),
    Tweet(id: 66, imageName: "66", correctAnswer: false),
    Tweet(id: 67, imageName: "67", correctAnswer: true),
    Tweet(id: 68, imageName: "68", correctAnswer: false),
    Tweet(id: 69, imageName: "69", correctAnswer: true),
    Tweet(id: 70, imageName: "70", correctAnswer: true),
    Tweet(id: 71, imageName: "71", correctAnswer: false),
    Tweet(id: 72, imageName: "72", correctAnswer: true),
    Tweet(id: 73, imageName: "73", correctAnswer: false),
    Tweet(id: 74, imageName: "74", correctAnswer: false),
    Tweet(id: 75, imageName: "75", correctAnswer: false),
    Tweet(id: 76, imageName: "76", correctAnswer: true),
    Tweet(id: 77, imageName: "77", correctAnswer: false),
    Tweet(id: 78, imageName: "78", correctAnswer: false),
    Tweet(id: 79, imageName: "79", correctAnswer: true)]
    
}
